//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioBusCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conductor
    {
        public string DNI { get; set; }
        public string nomComplet { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public int idLinia { get; set; }
    
        public virtual Linia Linia { get; set; }
    }
}
