//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioBusCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InteresTuristic
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string urlImg { get; set; }
        public string urlWeb { get; set; }
        public string direccio { get; set; }
        public int idParada { get; set; }
    
        public virtual Parada Parada { get; set; }
    }
}
